artifacts_root: artifacts 

data ingestion:
 root_dir: artifacts/data_ingestion
 source_URL: https://drive.google.com/file/d/1yVKnEnZeVZbQmKYG_nf1YD0SKFOQwdsu/view?usp=sharing
 local_data_file: artifacts/data_ingestion/zip
 unzip_path: artifacts/data_ingestion


